version: '3'

services:
  # Service for the Budget-App application
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/budget_app_db

  # Service for the PostgreSQL database
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: budget_app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
